# This file was generated by GoReleaser. DO NOT EDIT.
cask "aigw" do
  version "0.3.0"

  on_macos do
    on_arm do
      sha256 "5fa733c0c35ca63f46b7a1516f7447c511b5b076d27390539f857fb2d6d1f490"
      url "https://github.com/HengYangDS/aigw-cli/releases/download/v#{version}/aigw_#{version}_darwin_arm64.tar.gz"
      rename "aigw_0.3.0_darwin_arm64/aigw", "aigw"
    end
    on_intel do
      sha256 "777e2db25f32c278084783d2b3f24d365848730fb37861287b5477f5a3df58f2"
      url "https://github.com/HengYangDS/aigw-cli/releases/download/v#{version}/aigw_#{version}_darwin_amd64.tar.gz"
      rename "aigw_0.3.0_darwin_amd64/aigw", "aigw"
    end
  end
  on_linux do
    on_arm do
      sha256 "a7cf1b00eea68f2f80eceec1fef84c612d68f1c1536443212b05f28b99b69da5"
      url "https://github.com/HengYangDS/aigw-cli/releases/download/v#{version}/aigw_#{version}_linux_arm64.tar.gz"
      rename "aigw_0.3.0_linux_arm64/aigw", "aigw"
    end
    on_intel do
      sha256 "9389adba8b3002c048adf1eb0ed359a180794ed9ab8edb745e24ee8aad8102c1"
      url "https://github.com/HengYangDS/aigw-cli/releases/download/v#{version}/aigw_#{version}_linux_amd64.tar.gz"
      rename "aigw_0.3.0_linux_amd64/aigw", "aigw"
    end
  end

  name "aigw"
  desc "Local control plane for AI provider accounts and client configuration"
  homepage "https://github.com/HengYangDS/aigw-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aigw"

  # No zap stanza required

  caveats <<~EOS
    Run aigw setup to configure a provider and explicitly enable clients.
    Before uninstalling, run aigw status and aigw client disable <client>
    for each enabled client. Configuration and Tokens remain available.
  EOS
end
