# This file was generated by GoReleaser. DO NOT EDIT.
cask "aigw" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "d819b7896f1aa572403c84604275081a4c83ac620abb45b0440435824e4d3d59"
      url "https://github.com/HengYangDS/aigw-cli/releases/download/v#{version}/aigw_#{version}_darwin_arm64.tar.gz"
      rename "aigw_0.1.0_darwin_arm64/aigw", "aigw"
    end
    on_intel do
      sha256 "be299a83c456c21a73e157e6943b61490e9f9478c0fe2bfef2cf4216350229ff"
      url "https://github.com/HengYangDS/aigw-cli/releases/download/v#{version}/aigw_#{version}_darwin_amd64.tar.gz"
      rename "aigw_0.1.0_darwin_amd64/aigw", "aigw"
    end
  end
  on_linux do
    on_arm do
      sha256 "740717de4c0df6a76291d539c532a520d9aa297e9b2c9829bfd89ab666773d9d"
      url "https://github.com/HengYangDS/aigw-cli/releases/download/v#{version}/aigw_#{version}_linux_arm64.tar.gz"
      rename "aigw_0.1.0_linux_arm64/aigw", "aigw"
    end
    on_intel do
      sha256 "fdf95bdc37af350e66d51d63583341da050312be57b3f9bc03a716d473b19dde"
      url "https://github.com/HengYangDS/aigw-cli/releases/download/v#{version}/aigw_#{version}_linux_amd64.tar.gz"
      rename "aigw_0.1.0_linux_amd64/aigw", "aigw"
    end
  end

  name "aigw"
  desc "Local control plane for AI provider accounts and client configuration"
  homepage "https://github.com/HengYangDS/aigw-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aigw"

  # No zap stanza required

  caveats <<~EOS
    Run aigw setup to configure a provider and explicitly enable clients.
    Before uninstalling, run aigw adapter list and aigw adapter disable <client>
    for each enabled client. Configuration and Tokens remain available.
  EOS
end
