# This file was generated by GoReleaser. DO NOT EDIT.
cask "aigw" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "e5dd969ceb90f9ced799447b4e238ddcb2032032408b2437eefbf842712aa677"
      url "https://github.com/HengYangDS/aigw-cli/releases/download/v#{version}/aigw_#{version}_darwin_arm64.tar.gz"
      rename "aigw_0.2.0_darwin_arm64/aigw", "aigw"
    end
    on_intel do
      sha256 "5ef8568e8a2a5a03984aed82566a61648840cc30041c545b5aaaf6d0c102caee"
      url "https://github.com/HengYangDS/aigw-cli/releases/download/v#{version}/aigw_#{version}_darwin_amd64.tar.gz"
      rename "aigw_0.2.0_darwin_amd64/aigw", "aigw"
    end
  end
  on_linux do
    on_arm do
      sha256 "bfeed2564777f30a18600f7751df7f3445ae2304e5b1e727b43c84da993302e5"
      url "https://github.com/HengYangDS/aigw-cli/releases/download/v#{version}/aigw_#{version}_linux_arm64.tar.gz"
      rename "aigw_0.2.0_linux_arm64/aigw", "aigw"
    end
    on_intel do
      sha256 "5d7425a6e55fef294ac68f4f89d36281bc490f415d775e4f62c43879d9278ae5"
      url "https://github.com/HengYangDS/aigw-cli/releases/download/v#{version}/aigw_#{version}_linux_amd64.tar.gz"
      rename "aigw_0.2.0_linux_amd64/aigw", "aigw"
    end
  end

  name "aigw"
  desc "Local control plane for AI provider accounts and client configuration"
  homepage "https://github.com/HengYangDS/aigw-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aigw"

  # No zap stanza required

  caveats <<~EOS
    Run aigw setup to configure a provider and explicitly enable clients.
    Before uninstalling, run aigw status and aigw client disable <client>
    for each enabled client. Configuration and Tokens remain available.
  EOS
end
